import { query, mutation } from "./_generated/server";
import { v } from "convex/values";
import { DEFAULT_PHASES } from "./phaseDefaults";

// Shared validators for the nested phase structure. Stable ids (`key`, task
// `id`, choice `key`, option `value`, group `id`) are generated by the client
// and never rewritten, so customer progress that references them stays valid.
const optionValidator = v.object({ value: v.string(), label: v.string() });
const choiceValidator = v.object({
  key: v.string(),
  question: v.string(),
  options: v.array(optionValidator),
});
const taskValidator = v.object({
  id: v.string(),
  label: v.string(),
  details: v.optional(v.array(v.string())),
});
const groupValidator = v.object({
  id: v.string(),
  label: v.optional(v.string()),
  note: v.optional(v.string()),
  showWhen: v.optional(v.object({ key: v.string(), value: v.string() })),
  tasks: v.array(taskValidator),
});

export const list = query({
  args: {},
  handler: async (ctx) => {
    return await ctx.db.query("phases").withIndex("by_order").collect();
  },
});

// Seed the default onboarding phases — but only on a brand-new (empty) table,
// so phases the user has intentionally deleted are never resurrected.
export const seedIfEmpty = mutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("phases").take(1);
    if (existing.length > 0) return;
    let order = 0;
    for (const p of DEFAULT_PHASES) {
      await ctx.db.insert("phases", {
        key: p.key,
        order: order++,
        title: p.title,
        intro: p.intro,
        parallel: p.parallel,
        choices: p.choices,
        groups: p.groups,
      });
    }
  },
});

export const createPhase = mutation({
  args: { key: v.string(), title: v.string() },
  handler: async (ctx, { key, title }) => {
    const existing = await ctx.db.query("phases").collect();
    const order = existing.length;
    // Start with one empty group so "add task" always has a target.
    await ctx.db.insert("phases", {
      key,
      order,
      title,
      groups: [{ id: `${key}_g`, tasks: [] }],
    });
    return key;
  },
});

export const removePhase = mutation({
  args: { id: v.id("phases") },
  handler: async (ctx, { id }) => {
    const all = await ctx.db.query("phases").collect();
    if (all.length <= 1) {
      throw new Error("Keep at least one phase — you can't delete the last one.");
    }
    await ctx.db.delete(id);
    // Re-pack orders so they stay contiguous (0..n-1).
    const remaining = all
      .filter((p) => p._id !== id)
      .sort((a, b) => a.order - b.order);
    for (let i = 0; i < remaining.length; i++) {
      if (remaining[i].order !== i) {
        await ctx.db.patch(remaining[i]._id, { order: i });
      }
    }
  },
});

export const reorderPhases = mutation({
  args: { ids: v.array(v.id("phases")) },
  handler: async (ctx, { ids }) => {
    for (let i = 0; i < ids.length; i++) {
      await ctx.db.patch(ids[i], { order: i });
    }
  },
});

export const updatePhaseMeta = mutation({
  args: {
    id: v.id("phases"),
    title: v.string(),
    intro: v.optional(v.string()),
    parallel: v.optional(v.boolean()),
  },
  handler: async (ctx, { id, title, intro, parallel }) => {
    const trimmedIntro = intro?.trim();
    await ctx.db.patch(id, {
      title: title.trim() || "Untitled phase",
      intro: trimmedIntro ? trimmedIntro : undefined,
      parallel: parallel ? true : undefined,
    });
  },
});

export const setPhaseGroups = mutation({
  args: { id: v.id("phases"), groups: v.array(groupValidator) },
  handler: async (ctx, { id, groups }) => {
    await ctx.db.patch(id, { groups });
  },
});

export const setPhaseChoices = mutation({
  args: { id: v.id("phases"), choices: v.array(choiceValidator) },
  handler: async (ctx, { id, choices }) => {
    await ctx.db.patch(id, { choices: choices.length > 0 ? choices : undefined });
  },
});
